version: '3.8'

services:
  # Elevator Control System
  elevator-service:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    ports:
      - "6660:6660"  # Main API 
      - "6661:6661"  # WebSocket server
    environment:
      # Use development configuration for easier testing
      ENV: development
      LOG_LEVEL: DEBUG
      PORT: 6660
      
      # Enable features needed for the demo
      METRICS_ENABLED: "true"
      WEBSOCKET_ENABLED: "true"
      HEALTH_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ALLOWED_ORIGINS: "*"
      
      # Elevator configuration
      DEFAULT_MAX_FLOOR: 15
      DEFAULT_MIN_FLOOR: 0
      DEFAULT_ELEVATOR_COUNT: 3
      ELEVATOR_NAME_PREFIX: "Elevator"
      
      # Performance settings
      EACH_FLOOR_DURATION: 2s
      OPEN_DOOR_DURATION: 3s
      STATUS_UPDATE_INTERVAL: 1s
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6660/v1/health/live"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - elevator-network

  # Web server to serve the HTML client
  web-client:
    image: nginx:alpine
    ports:
      - "8080:80"  # Serve HTML client on port 8080
    volumes:
      - ./client_demo/client-docker.html:/usr/share/nginx/html/index.html:ro
      - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
    command: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf &&
             nginx -g 'daemon off;'"
    depends_on:
      elevator-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - elevator-network

networks:
  elevator-network:
    driver: bridge 